title: AE353 (Sp26)
description: Course website for AE353 (Sp26)
theme: just-the-docs

# Color scheme - options: nil (default), "dark", or custom
color_scheme: ae353

math: katex
url: https://uiuc-ae353.github.io
